# Generated by Django 6.0.2 on 2026-03-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('current_country', models.CharField(max_length=128)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='core.person')),
            ],
            options={
                'db_table': 'profiles_alumni_profile',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=64)),
                ('current_status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=32)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='core.person')),
            ],
            options={
                'db_table': 'profiles_student_profile',
            },
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to='core.person')),
            ],
            options={
                'db_table': 'profiles_supervisor_profile',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='core.person')),
            ],
            options={
                'db_table': 'profiles_teacher_profile',
            },
        ),
    ]
