# Generated by Django 6.0.2 on 2026-03-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SupervisorProfile',
        ),
    ]
