# Generated by Django 6.0.2 on 2026-03-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('Q1_MASTER_STATUS', 'Q1 Master status'), ('COLLECT_STUDENT_DATA', 'Collect student data'), ('Q2_INTERNSHIP', 'Q2 Internship (student)'), ('COLLECT_INTERNSHIP', 'Collect internship'), ('COLLECT_ALUMNI_DATA', 'Collect alumni data'), ('Q2_INTERNSHIP_ALUMNI', 'Q2 Internship (alumni)'), ('Q3_PHD', 'Q3 PhD'), ('COLLECT_PHD', 'Collect PhD'), ('Q4_WORK', 'Q4 Work'), ('COLLECT_WORK', 'Collect work'), ('SUBMIT', 'Submit')], default='Q1_MASTER_STATUS', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('base_role', models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('ALUMNI', 'Alumni')], max_length=32, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted')], default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_session', to='core.person')),
            ],
            options={
                'db_table': 'registration_registration_session',
            },
        ),
    ]
