# Generated by Django 6.0.2 on 2026-03-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('year', models.IntegerField()),
                ('venue', models.CharField(max_length=255)),
                ('doi_or_url', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'db_table': 'publications_publication',
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_publications', to='core.person')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='publications.publication')),
            ],
            options={
                'db_table': 'publications_publication_author',
            },
        ),
    ]
