# Generated by Django 6.0.2 on 2026-03-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STAGE', 'Stage'), ('DOCTORATE', 'Doctorate'), ('RESEARCH', 'Research'), ('JOB', 'Job'), ('OTHER', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('idea', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lab_name', models.CharField(blank=True, default='', max_length=255)),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=255)),
                ('keywords', models.TextField(blank=True, default='')),
                ('links', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_experiences', to='institutions.institution')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.person')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_experiences', to='core.person')),
            ],
            options={
                'db_table': 'experience_experience',
            },
        ),
    ]
