# Generated by Django 6.0.2 on 2026-03-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('UNIVERSITY', 'University'), ('LAB', 'Lab'), ('COMPANY', 'Company'), ('HOSPITAL', 'Hospital'), ('OTHER', 'Other')], max_length=32)),
                ('website', models.URLField(blank=True, default='')),
            ],
            options={
                'db_table': 'institutions_institution',
            },
        ),
    ]
